openapi: 3.0.1
info:
  title: ESXi AutoInstaller
  description: 'This tools helps you install multiple ESXi hosts automatically.'
  license:
    name: CISCO SAMPLE CODE LICENSE
    url: https://github.com/CiscoDevNet/esxi-auto-installer/blob/main/LICENSE
  version: 1.0.0
externalDocs:
  description: GitHub repository
  url: https://github.com/CiscoDevNet/esxi-auto-installer
servers:
- url: /api/v1
tags:
- name: jobs
- name: logs
- name: iso
paths:
  /jobs:
    get:
      tags:
      - jobs
      summary: Returns a list of jobs.
      description: Returns a list of all the jobs and their status.
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jobs'
    post:
      tags:
      - jobs
      summary: 'NOT IMPLEMENTED: Creates a new ESXi Installation job.'
      description: '**NOT IMPLEMENTED:** This endpoint has not yet been implemented.'
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/components/schemas/NewJob'

      responses:
        '200':
          description: successful operation
  /jobs/{jobID}:
    get:
      tags:
      - jobs
      summary: Returns details for a specific job.
      parameters:
      - name: jobID
        in: path
        description: ID of job.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatus'
    put:
      tags:
      - jobs
      summary: Updates a job entry.
      description: |
        Updates the status of a particular job.<BR>
        ```
         0: Ready to deploy
        10: Connecting to CIMC
        11: Mounting installation ISO
        15: Installation in progress
        18: Running cleanup tasks
        20: Finished
        30: Error
        31: Error: Failed to login to CIMC
        32: Error: Failed to mount installation ISO
        ```
      parameters:
      - name: jobID
        in: path
        description: ID of job.
        required: true
        schema:
          type: string
      - name: state
        in: query
        description: New job status
        required: true
        style: form
        explode: true
        schema:
          type: integer
          maximum: 32
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatus'
  /logs/{jobID}:
    get:
      tags:
      - logs
      summary: View job logs
      parameters:
      - name: jobID
        in: path
        description: ID of job.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: |
                  2022-01-01 07:07:07 GMT [INFO] Processing job ID: 172.17.20.79_1631556521.7252097, server Prefix-01-Suffix

                  2022-01-01 07:07:07 GMT [INFO] Generating kickstart file for server
                  2022-01-01 07:07:07 GMT [INFO] Generated kickstart configuration:
  /upload:
    post:
      tags:
      - iso
      summary: 'NOT IMPLEMENTED: Upload an ESXi Installation ISO'
      description: '**NOT IMPLEMENTED:** This endpoint has not yet been implemented.'
      responses:
        '200':
          description: OK
components:
  schemas:
    Jobs:
      description: "jobID is a unique string, default: {cimcip}_{timestamp}, eg. '192.168.0.1_1628871425.1136827'"
      type: object
      properties:
        jobID:
          $ref: '#/components/schemas/JobStatus'
    JobStatus:
      type: object
      properties:
        cimcip:
          type: "string"
          example: "192.168.0.111"
        finish_time:
          type: "string"
          example: "2022-01-01 08:08:08 GMT"
        hostname:
          type: "string"
          example: Prefix-01-Suffix
        ipaddr:
          type: "string"
          example: "192.168.2.11"
        start_time:
          type: "string"
          example: "2022-01-01 07:07:07 GMT"
        status:
          type: "string"
          example: "Installation in progress"
    NewJob:
      description: Submit new job
      type: object
      required:
      - iso_image
      - rootpw
      - cimc_usr
      - cimc_pwd
      - host_netmask
      - host_gateway
      - hosts
      properties:
        iso_image:
          type: string
          example: VMware-ESXi-7.0.0_U2-16324942-Custom
        rootpw:
          type: string
          format: password
        vlan:
          type: integer
          format: int32
          maximum: 4096
        vmnic:
          type: integer
          format: int32
        firstdisk:
          type: string
          enum: ['firstdiskfound', 'firstdisk', 'diskpath']
          default: 'firstdiskfound'
        firstdisktype: 
          type: string
          enum: ['local', 'remote', 'usb']
        diskpath:
          type: string
          example: naa.6d09466044143600247aee55ca2a6405
          # examples:
          #   scsi: 
          #     value: naa.6d09466044143600247aee55ca2a6405
          #   other:
          #     value: /vmfs/devices/disks/mpx.vmhba1:C0:T0:L0
        enablessh:
          type: boolean
          default: True
        clearpart:
          type: boolean
          default: False
        cimc_usr:
          type: string
        cimc_pwd:
          type: string
          format: password
        host_netmask:
          type: string
          example: 255.255.255.0
          default: 255.255.255.0
        host_gateway:
          type: string
          example: 192.168.2.1
        dns1:
          type: string
          example: 208.67.222.222
        dns2:
          type: string
          example: 207.67.220.220
        static_routes:
          type: array
          items:
            type: object
            required:
            - subnet
            - mask
            - gateway
            properties:
              subnet:
                type: string
                example: 172.16.10.0
              mask:
                type: integer
                example: 24
                minimum: 3
                maximum: 32
              gateway:
                type: string
                example: 192.168.0.251
        hosts:
          type: array
          items:
            type: object
            required:
            - hostname
            - ipaddr
            - cimcip
            properties:
              hostname:
                type: string
                example: esxi-01-hostname
              ipaddr:
                type: string
                example: 192.168.2.11
              cimcip:
                type: string
                example: 192.168.0.111
