openapi: 3.0.1
info:
  title: ESXi AutoInstaller
  description: 'This tools helps you install multiple ESXi hosts automatically.'
  license:
    name: CISCO SAMPLE CODE LICENSE
    url: https://github.com/CiscoDevNet/esxi-auto-installer/blob/main/LICENSE
  version: 1.0.0
externalDocs:
  description: GitHub repository
  url: https://github.com/CiscoDevNet/esxi-auto-installer
servers:
- url: /api/v1
tags:
- name: jobs
- name: logs
- name: iso
paths:
  /jobs:
    get:
      tags:
      - jobs
      summary: Returns a list of jobs.
      description: Returns a list of all the jobs and their status.
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jobs'
    post:
      tags:
      - jobs
      summary: 'Creates a new ESXi Installation job.'
      description: |
        Take installation details as json payload and create installation job per each host in 'hosts' list.
        ```
        {
          "iso_image": "VMware-ESXi-7.0.0_U2-16324942-Custom-Cisco-4.1.2a", 
          "rootpw": "r00t5ecRet!", 
          "cimc_usr": "admin", 
          "cimc_pwd": "@dm1n5ecRet!", 
          "vlan": "0", 
          "host_netmask": "255.255.255.0", 
          "host_gateway": "172.17.14.254", 
          "hosts": 
          [
            {"hostname": "demo-server-01", "ipaddr": "10.10.10.111", "cimcip": "192.168.100.11"}, 
            {"hostname": "demo-server-02", "ipaddr": "10.10.10.112", "cimcip": "192.168.100.12"}, 
            {"hostname": "demo-server-03", "ipaddr": "10.10.10.113", "cimcip": "192.168.100.13"}
          ]
        }
        ```
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobIDs'
  /jobs/{jobID}:
    get:
      tags:
      - jobs
      summary: Returns details for a specific job.
      parameters:
      - name: jobID
        in: path
        description: ID of job.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatus'
    put:
      tags:
      - jobs
      summary: Updates a job entry.
      description: |
        Updates the status of a particular job.<BR>
        ```
         0: Ready to deploy
        10: Connecting to CIMC
        11: Mounting installation ISO
        15: Installation in progress
        18: Running cleanup tasks
        20: Finished
        30: Error
        31: Error: Failed to login to CIMC
        32: Error: Failed to mount installation ISO
        ```
      parameters:
      - name: jobID
        in: path
        description: ID of job.
        required: true
        schema:
          type: string
      - name: state
        in: query
        description: New job status
        required: true
        style: form
        explode: true
        schema:
          type: integer
          maximum: 32
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatus'
  /logs/{jobID}:
    get:
      tags:
      - logs
      summary: View job logs
      parameters:
      - name: jobID
        in: path
        description: ID of job.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: |
                  2022-01-01 07:07:07 GMT [INFO] Processing job ID: 172.17.20.79_1631556521.7252097, server Prefix-01-Suffix

                  2022-01-01 07:07:07 GMT [INFO] Generating kickstart file for server
                  2022-01-01 07:07:07 GMT [INFO] Generated kickstart configuration:
  /isos:
    get:
      tags:
      - iso
      summary: Get a list of available ESXi Installation ISO(s)
      description: |
        List of available installation ISOs:<br>
        ```
        [
          "VMware-ESXi-6.5.0_U3_Installer-13932383",
          "VMware-ESXi-6.7.0_U3_Installer-14320388"
        ]
        ```
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IsoList'
components:
  schemas:
    Jobs:
      description: "jobID is a unique string, default: {cimcip}_{timestamp}, eg. '192.168.0.1_1628871425.1136827'"
      type: object
      properties:
        jobID:
          $ref: '#/components/schemas/JobStatus'
    JobStatus:
      type: object
      properties:
        cimcip:
          type: "string"
          example: "192.168.0.1"
        finish_time:
          type: "string"
          example: "2022-01-01 08:08:08 GMT"
        hostname:
          type: "string"
          example: Prefix-01-Suffix
        ipaddr:
          type: "string"
          example: "192.168.0.2"
        start_time:
          type: "string"
          example: "2022-01-01 07:07:07 GMT"
        status:
          type: "string"
          example: "Installation in progress"
    JobIDs:
      description: "List of job IDs"
      type: object
      properties:
        jobID:
          type: "string"
          example: "192.168.0.1_1628871425.1136827"      
    IsoList:
      description: "List of available ISO images"
      type: object
      properties:
        ISO:
          type: "string"
          example: "VMware-ESXi-6.5.0_U3_Installer-13932383"