# VMware Auto-Installer config
DOCROOT= '/var/www/demo/'
VMAI_DB = DOCROOT + 'vmai_db.json'
VMAI_LOG = '/opt/vmai/log/vmai.log'
DHCPCFG = '/etc/dhcp/dhcpd.conf'
TFTPBOOT = '/tftpboot/'
UPLOADDIR = DOCROOT + 'upload/'
TMPISODIR = DOCROOT + 'upload/mnt/'
TFTPISODIR = TFTPBOOT + 'iso/'
KSDIR = TFTPBOOT + 'ks/'
PXEDIR = TFTPBOOT + 'pxelinux.cfg/'
KSTEMPLATE = DOCROOT + 'templates/kickstart.jinja'
PXETEMPLATE = DOCROOT + 'templates/pxecfg_template'
DHCPTEMPLATE = DOCROOT + 'templates/dhcp_template'