openapi: 3.0.1
info:
  title: ESXi AutoInstaller
  description: 'This tools helps you install multiple ESXi hosts automatically.'
  license:
    name: CISCO SAMPLE CODE LICENSE
    url: https://github.com/CiscoDevNet/esxi-auto-installer/blob/main/LICENSE
  version: 1.0.0
externalDocs:
  description: GitHub repository
  url: https://github.com/CiscoDevNet/esxi-auto-installer
servers:
- url: /api/v1
tags:
- name: jobs
- name: logs
- name: iso
paths:
  /jobs:
    get:
      tags:
      - jobs
      summary: Returns a list of jobs.
      description: Returns a list of all the jobs and their status.
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jobs'
    post:
      tags:
      - jobs
      summary: 'NOT IMPLEMENTED: Creates a new ESXi Installation job.'
      description: '**NOT IMPLEMENTED:** This endpoint has not yet been implemented.'
      responses:
        '200':
          description: successful operation
  /jobs/{jobId}:
    get:
      tags:
      - jobs
      summary: Returns a specific job.
      parameters:
      - name: jobId
        in: path
        description: ID of job.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatus'
    put:
      tags:
      - jobs
      summary: Updates a job entry.
      description: | 
        Updates the status of a particular job.<BR>
        ```
         0: Ready to deploy
        10: Connecting to CIMC
        11: Mounting installation ISO
        15: Installation in progress
        18: Running cleanup tasks
        20: Finished
        30: Error
        31: Error: Failed to login to CIMC
        32: Error: Failed to mount installation ISO
        ```
      parameters:
      - name: jobId
        in: path
        description: ID of job.
        required: true
        schema:
          type: string
      - name: state
        in: query
        description: New job status
        required: true
        style: form
        explode: true
        schema:
          type: integer
          maximum: 32
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatus'
  /logs/{jobId}:
    get:
      tags:
      - logs
      summary: View job logs
      parameters:
      - name: jobId
        in: path
        description: ID of job.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: |
                  2022-01-01 07:07:07 GMT [INFO] Processing job ID: 172.17.20.79_1631556521.7252097, server Prefix-01-Suffix

                  2022-01-01 07:07:07 GMT [INFO] Generating kickstart file for server
                  2022-01-01 07:07:07 GMT [INFO] Generated kickstart configuration:
  /upload:
    post:
      tags:
      - iso
      summary: 'NOT IMPLEMENTED: Upload an ESXi Installation ISO'
      description: '**NOT IMPLEMENTED:** This endpoint has not yet been implemented.'
      responses:
        '200':
          description: OK
components:
  schemas:
    Jobs:
      type: "object"
      additionalProperties:
        $ref: '#/components/schemas/JobStatus'

    JobStatus:
      type: object
      properties:
        cimcip:
          type: "string"
          example: "192.168.0.1"
        finish_time:
          type: "string"
          example: "2022-01-01 08:08:08 GMT"
        hostname:
          type: "string"
          example: Prefix-01-Suffix
        ipaddr:
          type: "string"
          example: "192.168.0.2"
        start_time:
          type: "string"
          example: "2022-01-01 07:07:07 GMT"
        status:
          type: "string"
          example: "Installation in progress"